### ISSUE TITLE
센터 최상위 부서 추가시 알럿 안뜨도록 수정 

### ISSUE THREAD

**Issue by jullee96** [hamonikr/hamonize#137]
### 개요 ###
- 센터

### 이슈 종류를 선택해주세요 ###
[ V ] New Feature
[  ] Bug Fix

### 내용 ###
-  센터에서 최초에 최상위 부서 등록시 [+부서 추가] 클릭시 "상위부서 선택해주세요" 라는 얼럿 발생하는 기존 로직 수정필요

**Comment by gon1942** [comment]
#137 이슈 반영 완료
