### ISSUE TITLE
서비스 아키텍처 구성도 작성

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonize#31]
하모나이즈 서비스 전체가 어떻게 구성되는지 볼 수 있는 아키텍처 구성도를 작성해주세요

1) 각 부분의 아키텍처를 작성
2) 부문별 작성한 아키텍처를 하나의 다이어그램으로 구성
3) 문서로 작성해서 저장소에 반영

**Comment by jullee96** [comment]
@chaeya 
아키텍처 이미지를 수정하였습니다
https://github.com/hamonikr/hamonize/pull/39
