### ISSUE TITLE
컨트리뷰터 자동 추가되는 봇 적용

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonize#32]
@yeji0407 
https://allcontributors.org/docs/en/bot/usage

**Comment by yeji0407** [comment]
해당 봇을 추가하고 모든 기여자를 리스트에 추가하였습니다.

**Comment by chaeya** [comment]
@all-contributors add @choonsik2

**Comment by chaeya** [comment]
@all-contributors add @choonsik2 code

**Comment by chaeya** [comment]
@all-contributors add @bigeden
@all-contributors add @gon1942

**Comment by chaeya** [comment]
@all-contributors add @gon1942

**Comment by bigeden** [comment]
@all-contributors add @bigeden code

**Comment by bigeden** [comment]
@all-contributors add @gon1942  code
