### ISSUE TITLE
프로그램 매뉴얼 작성

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonize#35]
GS인증을 요청하기 위해서는 프로그램의 매뉴얼을 먼저 준비해야 빠르게 진행할 수 있기 때문에 
인증대상에 대한 매뉴얼을 작성해야 합니다.

기존 매뉴얼이 있는지 확인하고, 새로 출시할 버전에 맞는 매뉴얼을 작성해주세요.

**Comment by yeji0407** [comment]
아래 링크에서 하모나이즈 매뉴얼을 작성중입니다.
http://pms.invesume.com:8090/pages/viewpage.action?pageId=73339494&src=contextnavpagetreemode

**Comment by chaeya** [comment]
@yeji0407 매뉴얼의 내용중 이미지를 삽입할때 전체 이미지를 사용하지 말고(너무 작은 글씨로 식별이 어려움) 설명에 해당하는 부분의 이미지만 보여주는 것이 좋을것 같습니다.
