### ISSUE TITLE
개선해야 할 항목을 작성하고 우선순위 부여

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonize#46]
하모나이즈 0.1 릴리즈를 대상으로 개선할 내용을 재작성하고 우선순위 부여

우선순위는 아래의 기준에 따라서 부여할 것
 1) 프로젝트 계획서에 있는 내용
 2) 기능 및 성능 개선 사항
 3) 배포 편의성 제공을 위한 사항
 4) 클라우드 서비스 제공을 위한 개선 사항

@jullee96 
도출한 내용을 컨플루언스 스페이스에서 관리해주세요.

**Comment by jullee96** [comment]
[하모나이즈 개선사항](http://pms.invesume.com:8090/pages/viewpage.action?pageId=73338614) 에서 관리하도록 하겠습니다
