### ISSUE TITLE
README 의 Table of Contents 목차에 Contributing 링크 미동작

### ISSUE THREAD

**Issue by kangjung** [hamonikr/hamonize#517]
### 개요 ###
- README 의 Table of Contents 목차에 Contributing 링크 미동작

### 이슈 종류를 선택해주세요 ###
[ ] New Feature
[v] Bug Fix

### 내용 ###
- README 의 Table of Contents 목차에 Contributing 링크가 미동작 하는 것 같습니다.
![image](https://user-images.githubusercontent.com/28768760/166653588-a1619ec2-949b-4ac4-9bb6-4e1688728803.png)

**Comment by gon1942** [comment]
안녕하세요...이슈처리가 늦어져서 죄송합니다.
